### ISSUE TITLE
Allow x-ms-client-name on operations

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#118]
So there is an easy way to rename client methods.

**Comment by fearthecowboy** [comment]
`4.3.124`  now supports x-ms-client-name on operations : 
https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/a-playground/modeler.yaml#L1930

**Comment by pakrym** [comment]
```
{
  "swagger": "2.0",
  "info": {
    "title": "AutoRest Parameter Flattening",
    "description": "Resource Flattening for AutoRest",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "consumes": [
    "application/json"
  ],
  "paths": {
    "/originalOperation/{originalPathParameter}": {
      "patch": {
        "operationId": "originalOperation",
>>>        "x-ms-client-name": "RenamedOperation",
        "parameters": [
          {
            "name": "originalPathParameter",
            "in": "path",
            "required": true,
            "type": "string",
            "x-ms-client-name": "RenamedPathParameter"
          },
          {
            "name": "originalQueryParameter",
            "x-ms-client-name": "RenamedQueryParameter",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "originalBodyParameter",
            "x-ms-client-name": "RenamedBodyParameter",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OriginalSchema"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/OriginalSchema"
            },
            "headers": {
              "originalHeader": {
                  "x-ms-client-name": "RenamedHeader",
                  "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "OriginalSchema": {
      "type":  "object",
      "properties": {
        "originalProperty": {
          "type": "object",
          "title": "A set of tags.",
          "x-ms-client-name": "RenamedProperty",
          "description": "A description about the set of tags.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "originalPropertyString": {
          "type": "string",
          "title": "A set of tags.",
          "x-ms-client-name": "RenamedPropertyString",
          "description": "A description about the set of tags."
        }
      },
      "required": [
        "tags"
      ]
    }
  }
}

```
```
 Loading AutoRest extension '@autorest/modelerfour' (4.3.124->4.3.124)
   Including extension configuration file 'file:///C:/Users/pakrym/.autorest/@autorest_modelerfour@4.3.124/node_modules/@autorest/modelerfour/readme.md'
   Loading local AutoRest extension '@autorest/csharp-v3' (D:\github\azure\autorest.csharp\test\TestServerProjects\..\..\)
   Including extension configuration file 'file:///D:/github/azure/autorest.csharp/readme.md'
DEBUG [19.07 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [19.07 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [19.07 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [19.07 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [19.08 s]: pipeline-emitter - START inputs = 0
DEBUG [19.12 s]: configuration-emitter - START inputs = 0
DEBUG [19.18 s]: pipeline-emitter - END [0.1 s]
DEBUG [19.18 s]: configuration-emitter - END [0.1 s]
DEBUG [19.19 s]: openapi-document-override/md-override-loader-openapi - END [0.12 s]
DEBUG [19.19 s]: swagger-document-override/md-override-loader-swagger - END [0.12 s]
VERBOSE [19.19 s]: Reading OpenAPI 2.0 file file:///D:/github/azure/autorest.csharp/test/swaggers/extension-client-name.json
DEBUG [19.2 s]: openapi-document/loader-openapi - END [0.12 s]
DEBUG [19.2 s]: openapi-document/individual/transform - SKIPPING
DEBUG [19.2 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [19.2 s]: openapi-document/individual/identity - SKIPPING
DEBUG [19.21 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [19.21 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [19.21 s]: swagger-document/loader-swagger - END [0.14 s]
DEBUG [19.22 s]: swagger-document/individual/transform - START inputs = 1
DEBUG [19.22 s]: swagger-document/individual/transform - END [0 s]
DEBUG [19.22 s]: swagger-document/individual/schema-validator-swagger - START inputs = 1
ERROR: Schema violation: Additional properties not allowed: x-ms-client-name
    - file:///D:/github/azure/autorest.csharp/test/swaggers/extension-client-name.json:1:1
C:\Users\pakrym\.autorest\@autorest_core@3.0.6185\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
ERROR: Schema violation: Additional properties not allowed: x-ms-client-name
    - file:///D:/github/azure/autorest.csharp/test/swaggers/extension-client-name.json:1:1
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting. / Error: [OperationAbortedException] Error occurred. Exiting.
    at C:\Users\pakrym\.autorest\@autorest_core@3.0.6185\node_modules\@autorest\core\dist\lib\pipeline\schema-validation.js:31:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\pakrym\.autorest\@autorest_core@3.0.6185\node_modules\@autorest\core\dist\lib\pipeline\common.js:26:29
    at async ScheduleNode (C:\Users\pakrym\.autorest\@autorest_core@3.0.6185\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:291:33)
```

**Comment by fearthecowboy** [comment]
I hate that schema validation some times

**Comment by fearthecowboy** [comment]
autorest core `3.0.6187` has an updated schema
