### ISSUE TITLE
error reported when the format is int32 for type 'number'

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.modelerfour#135]
following error reported when running autorest against ...\azure-rest-api-specs\specification\cosmos-db\resource-manager\readme.md
----

PLUGIN FAILURE: Unrecognized schema type:'number' / format: int32 {"readOnly":true,"type":"number","format":"int32","description":"The number of values for the metric."} , Error: Unrecognized schema type:'number' / format: int32 {"readOnly":true,"type":"number","format":"int32","description":"The number of values for the metric."} 
    at should (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:670:19)
    at ModelerFour.should (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:34:60)
    at ModelerFour.processSchema (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:525:21)
    at use (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:402:36)
    at ModelerFour.use (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:46:20)
    at ModelerFour.createObjectSchema (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:401:18)
    at ModelerFour.processObjectSchema (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:444:35)
    at should (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:626:33)
    at ModelerFour.should (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:34:60)
    at ModelerFour.processSchema (c:\git\autorest.modelerfour\modelerfour\dist\modeler\modelerfour.js:525:21), {}

**Comment by fearthecowboy** [comment]
Already fixed in `4.3.144`
