### ISSUE TITLE
[Cognitive Form Recognizer] "FATAL: Error: Not able to process media type */* at this moment"

### ISSUE THREAD

**Issue by kristapratico** [Azure/autorest.modelerfour#155]
**Describe the issue**
Encountered this error when trying to generate v2.0 of Form Recognizer from the azure-rest-api-spec repo. The generation works with version 2 of autorest.

![autorest3](https://user-images.githubusercontent.com/31998003/73886665-e10a7880-481e-11ea-8970-578298fd112a.PNG)

** REQUIRED ** 
**ModelerFour** version: 4.4.162
**AutoRest-core** version: 3.0.6146
**CommandLine** : `autorest-beta --python --use=C:\Users\krpratic\autorestv3\autorest.python --tag=release_2_0 --output-folder=FormRecognizer/`
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json

**Comment by fearthecowboy** [comment]
can you do a `--debug --verbose ` with that?  I suspect that it's looking at an operation that's missing a consumes or produces, and it doesn't like the fact that the swagger loader is guessing.

**Comment by kristapratico** [comment]
Here's the output:

AutoRest code generation utility [version: 3.0.6146; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\krpratic\.autorest\@autorest_core@3.0.6198
   Loading AutoRest core      'C:\Users\krpratic\.autorest\@autorest_core@3.0.6198\node_modules\@autorest\core\dist' (3.0.6198)
   Initial configuration file 'file:///C:/Users/krpratic/azure-rest-api-specs/specification/cognitiveservices/data-plane/FormRecognizer/readme.md'
   Including configuration file 'file:///C:/Users/krpratic/azure-rest-api-specs/specification/cognitiveservices/data-plane/FormRecognizer/readme.python.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/directives.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/pipeline.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/loader-openapi.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/markdown-documentation.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/miscellaneous.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/patches.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-powershell.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-csharp.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-go.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-java.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-nodejs.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-php.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-python.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-ruby.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-typescript.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-validators.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-az.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/plugin-terraform.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/graphs.md'
   Including configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_core@3.0.6198/node_modules/@autorest/core/resources/help-configuration.md'
   Including extension configuration file 'file:///C:/Users/krpratic/autorestv3/autorest.python/README.md'
   Including extension configuration file 'file:///C:/Users/krpratic/.autorest/@autorest_modelerfour@4.4.162/node_modules/@autorest/modelerfour/readme.md'
DEBUG [5.72 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [5.72 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [5.72 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [5.72 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [5.72 s]: pipeline-emitter - START inputs = 0
DEBUG [5.82 s]: configuration-emitter - START inputs = 0
DEBUG [5.87 s]: pipeline-emitter - END [0.15 s]
DEBUG [5.87 s]: configuration-emitter - END [0.15 s]
DEBUG [5.94 s]: openapi-document-override/md-override-loader-openapi - END [0.22 s]
DEBUG [5.94 s]: swagger-document-override/md-override-loader-swagger - END [0.22 s]
VERBOSE [5.95 s]: Reading OpenAPI 2.0 file file:///C:/Users/krpratic/azure-rest-api-specs/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json
DEBUG [5.97 s]: openapi-document/loader-openapi - END [0.25 s]
DEBUG [5.97 s]: openapi-document/individual/transform - SKIPPING
DEBUG [5.97 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [5.97 s]: openapi-document/individual/identity - SKIPPING
DEBUG [5.98 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [5.98 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [6.06 s]: swagger-document/loader-swagger - END [0.34 s]
DEBUG [6.06 s]: swagger-document/individual/transform - START inputs = 1
DEBUG [6.08 s]: swagger-document/individual/transform - END [0.01 s]
DEBUG [6.08 s]: swagger-document/individual/schema-validator-swagger - START inputs = 1
DEBUG [6.13 s]: swagger-document/individual/schema-validator-swagger - END [0.05 s]
DEBUG [6.13 s]: swagger-document/identity - START inputs = 1
DEBUG [6.13 s]: swagger-document/individual/identity - START inputs = 1
DEBUG [6.13 s]: swagger-document/identity - END [0 s]
DEBUG [6.14 s]: swagger-document/individual/identity - END [0 s]
DEBUG [6.14 s]: openapi-document/openapi-document-converter - START inputs = 1
DEBUG [6.19 s]: openapi-document/openapi-document-converter - END [0.05 s]
DEBUG [6.19 s]: openapi-document/transform - START inputs = 2
DEBUG [6.2 s]: openapi-document/transform - END [0 s]
DEBUG [6.2 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [6.2 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [6.2 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [6.26 s]: openapi-document/tree-shaker - END [0.06 s]
DEBUG [6.27 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [6.37 s]: openapi-document/multi-api-merger - END [0.1 s]
DEBUG [6.37 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [6.47 s]: openapi-document/components-cleaner - END [0.09 s]
DEBUG [6.47 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [6.49 s]: openapi-document/component-modifiers - END [0.01 s]
DEBUG [6.49 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [6.49 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [6.49 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [6.49 s]: openapi-document/profile-filter - END [0 s]
DEBUG [6.49 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [6.49 s]: openapi-document/emitter - START inputs = 1
DEBUG [6.5 s]: openapi-document/emitter - END [0 s]
DEBUG [6.98 s]: openapi-document/model-deduplicator - END [0.48 s]
DEBUG [6.98 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [7.06 s]: openapi-document/enum-deduplicator - END [0.07 s]
DEBUG [7.06 s]: openapi-document/subset-reducer - START inputs = 1
DEBUG [7.11 s]: openapi-document/subset-reducer - END [0.05 s]
DEBUG [7.11 s]: openapi-document/quick-check - START inputs = 1
DEBUG [7.11 s]: openapi-document/multi-api/reset-identity - START inputs = 1
DEBUG [7.13 s]: openapi-document/quick-check - END [0.02 s]
DEBUG [7.13 s]: openapi-document/multi-api/reset-identity - END [0.02 s]
DEBUG [7.13 s]: openapi-document/multi-api/identity - START inputs = 1
DEBUG [7.13 s]: openapi-document/multi-api/identity - END [0 s]
DEBUG [7.14 s]: openapi-document/multi-api/emitter - START inputs = 1
DEBUG [7.14 s]: modelerfour - START inputs = 1
DEBUG [7.14 s]: openapi-document/multi-api/emitter - END [0 s]
C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\plugin-modelerfour.js - FAILURE  {} Error: Not able to process media type */* at this moment.
    at ModelerFour.filterMediaTypes (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:731:31)
    at should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:1021:46)
    at ModelerFour.should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:42:60)
    at ModelerFour.processOperation (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:739:21)
    at should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:1124:30)
    at ModelerFour.should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:42:60)
    at ModelerFour.process (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:1122:22)
    at processRequest (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\plugin-modelerfour.js:19:35)
PLUGIN FAILURE: Not able to process media type */* at this moment., Error: Not able to process media type */* at this moment.
    at ModelerFour.filterMediaTypes (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:731:31)
    at should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:1021:46)
    at ModelerFour.should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:42:60)
    at ModelerFour.processOperation (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:739:21)
    at should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:1124:30)
    at ModelerFour.should (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:42:60)
    at ModelerFour.process (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\modelerfour.js:1122:22)
    at processRequest (C:\Users\krpratic\.autorest\@autorest_modelerfour@4.4.162\node_modules\@autorest\modelerfour\dist\modeler\plugin-modelerfour.js:19:35), {}
FATAL: Error: Not able to process media type */* at this moment.
C:\Users\krpratic\.autorest\@autorest_core@3.0.6198\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin modelerfour reported failure. / Error: Plugin modelerfour reported failure.
    at C:\Users\krpratic\.autorest\@autorest_core@3.0.6198\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin modelerfour reported failure.
[7.22 s] Shutting Down.
[7.22 s] Exiting.

**Comment by fearthecowboy** [comment]
Ah. I see what's going on.

There are operations that have no 'produces' yet, have responses that have a `default ` response that has a schema.

example: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json#L209

The V2 modeler blindly looked past that, but that's not ok. Responses have to be able to be matched with a incoming media type

**Comment by fearthecowboy** [comment]
The swagger needs to be updated.

**Comment by johanste** [comment]
Responses [SHOULD be accompanied by a relevant produces mime-type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#response-object). So while it probably would be worthwhile updating the swagger, autorest probably also should give you a warning rather than exploding.

**Comment by daviwil** [comment]
Looks like @kristapratico fixed this issue in a PR to the Swagger: https://github.com/Azure/azure-rest-api-specs/pull/8814.  I'll see if I can add a warning in AutoRest Core to encourage the use of `produces` on operations that return a body payload.

**Comment by vinagesh** [comment]
I just hit the same issue and the error message was not very clear. I compared my current swagger with another working one to find out that the error had to do with schema around "produces" and "consumes". It would be great to have a clear error message.
