### ISSUE TITLE
Failed to generate Microsoft.ContainerService/stable/2017-01-31/containerService.json

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#167]
**Describe the issue**

Failed to generate Microsoft.ContainerService/stable/2017-01-31/containerService.json

Error message:
```
DEBUG [8.29 s]: modelerfour/pre-namer - START inputs = 2
C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\plugin-prenamer.js - FAILURE  {} TypeError: identifier is not iterable
    at Object.removeSequentialDuplicates (/node_modules/@azure-tools/codegen/dist/text-manipulation.js:228:21)
    at normalize (/node_modules/@azure-tools/codegen/dist/formatter.js:50:181)
    at pascal (/node_modules/@azure-tools/codegen/dist/formatter.js:96:53)
    at /node_modules/@azure-tools/codegen/dist/formatter.js:41:25
    at setName (C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\prenamer.js:21:35)
    at PreNamer.process (C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\prenamer.js:84:17)
    at processRequest (C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\plugin-prenamer.js:19:31)
PLUGIN FAILURE: identifier is not iterable, TypeError: identifier is not iterable
    at Object.removeSequentialDuplicates (/node_modules/@azure-tools/codegen/dist/text-manipulation.js:228:21)
    at normalize (/node_modules/@azure-tools/codegen/dist/formatter.js:50:181)
    at pascal (/node_modules/@azure-tools/codegen/dist/formatter.js:96:53)
    at /node_modules/@azure-tools/codegen/dist/formatter.js:41:25
    at setName (C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\prenamer.js:21:35)
    at PreNamer.process (C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\prenamer.js:84:17)
    at processRequest (C:\Users\weidxu\.autorest\@autorest_modelerfour@4.6.199\node_modules\@autorest\modelerfour\dist\prenamer\plugin-prenamer.js:19:31), {}
FATAL: TypeError: identifier is not iterable
```

** REQUIRED ** 
**ModelerFour** version: 4.6.199
**AutoRest-core** version: 3.0.6220
**CommandLine** : `autorest-beta --version=3.0.6220 --payload-flattening-threshold=1 --input-file=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/compute/resource-manager/Microsoft.ContainerService/stable/2017-01-31/containerService.json`
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/compute/resource-manager/Microsoft.ContainerService/stable/2017-01-31/containerService.json

**Comment by fearthecowboy** [comment]
Ach! looks like a non-x-ms-enum didn't force the value to a string. Fixing...

**Comment by fearthecowboy** [comment]
Try `v4.6.200 ` (I did a hot-patch directly on github, I'm in the middle of other work, so I couldn't test it myself) .

**Comment by weidongxu-microsoft** [comment]
v4.6.200 is good. Thanks.
