### ISSUE TITLE
Unable to generate model for Microsoft.Storage: Duplicate object schemas

### ISSUE THREAD

**Issue by rjmholt** [Azure/autorest.modelerfour#303]
Running the `CommandLine` below, I get the following output:

```
DEBUG [8.28 s]: modelerfour - END [0.63 s]
DEBUG [8.28 s]: modelerfour/new-transform - START inputs = 2
DEBUG [8.28 s]: modelerfour/new-transform - END [0 s]
DEBUG [8.28 s]: modelerfour/flattener - START inputs = 2
DEBUG [8.61 s]: modelerfour/flattener - END [0.32 s]
DEBUG [8.61 s]: modelerfour/flattener/new-transform - START inputs = 2
DEBUG [8.61 s]: modelerfour/flattener/new-transform - END [0 s]
DEBUG [8.61 s]: modelerfour/grouper - START inputs = 2
DEBUG [8.91 s]: modelerfour/grouper - END [0.29 s]
DEBUG [8.91 s]: modelerfour/grouper/new-transform - START inputs = 2
DEBUG [8.91 s]: modelerfour/grouper/new-transform - END [0 s]
DEBUG [8.91 s]: modelerfour/pre-namer - START inputs = 2
DEBUG [9.2 s]: modelerfour/pre-namer - END [0.28 s]
DEBUG [9.2 s]: modelerfour/pre-namer/new-transform - START inputs = 2
DEBUG [9.2 s]: modelerfour/pre-namer/new-transform - END [0 s]
DEBUG [9.2 s]: modelerfour/checker - START inputs = 2

WARNING (): Schema Missing Name '{"type":"constant","value":{"value":"default"},"valueType":{"type":"string","language":{"default":{"name":"string","description":"simple string"}},"protocol":{}},"language":{"default":{"name":"","description":""}},"protocol":{}}'.
C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js - FAILURE  {} Error: 4 errors occured -- cannot continue.
    at Session.checkpoint (/node_modules/@azure-tools/autorest-extension-base/dist/convenience.js:158:19)
    at processRequest (C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js:21:17)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17

ERROR (): Duplicate object schemas with 'BlobServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'FileServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'QueueServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'TableServiceProperties' name  detected.
PLUGIN FAILURE: 4 errors occured -- cannot continue., Error: 4 errors occured -- cannot continue.
    at Session.checkpoint (/node_modules/@azure-tools/autorest-extension-base/dist/convenience.js:158:19)
    at processRequest (C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js:21:17)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17, {}
FATAL: Error: 4 errors occured -- cannot continue.
C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin checker reported failure. / Error: Plugin checker reported failure.
    at C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
    at async ScheduleNode (C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Plugin checker reported failure.
```

I don't fully understand the output or whether I'm reporting it in the right place, but I'm trying to run my own code generator (based on [this one](https://github.com/fearthecowboy/autorest.sputnik/tree/simple)) on one of the more common Azure resource providers and autorest seems to be falling down before it reaches my plugin.

- Is my assessment accurate, or does this look like a bug in my code?
- Is there any way I could fix or work around this on my end?
- What seems to be the issue here?

** REQUIRED ** 
**ModelerFour** version: 4.13.312
**AutoRest-core** version:  3.0.6282
**CommandLine** : `autorest https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager --use:.  --tag=package-2019-06 --debug`
OpenAPI/Swagger file: (Not sure what this refers to but happy to provide it)

**Comment by rjmholt** [comment]
Hey @daviwil, I'm back to working on this but still hitting the same issue:

```
WARNING (): Schema Missing Name '{"type":"constant","value":{"value":"default"},"valueType":{"type":"string","language":{"default":{"name":"string","description":"simple string"}},"protocol":{}},"language":{"default":{"name":"","description":""}},"protocol":{}}'.
C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js - FAILURE  {} Error: 4 errors occured -- cannot continue.
    at Session.checkpoint (/node_modules/@azure-tools/autorest-extension-base/dist/convenience.js:158:19)
    at processRequest (C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js:21:17)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17

ERROR (): Duplicate object schemas with 'BlobServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'FileServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'QueueServiceProperties' name  detected.

ERROR (): Duplicate object schemas with 'TableServiceProperties' name  detected.
PLUGIN FAILURE: 4 errors occured -- cannot continue., Error: 4 errors occured -- cannot continue.
    at Session.checkpoint (/node_modules/@azure-tools/autorest-extension-base/dist/convenience.js:158:19)
    at processRequest (C:\Users\Robert Holt\.autorest\@autorest_modelerfour@4.13.312\node_modules\@autorest\modelerfour\dist\checker\plugin-checker.js:21:17)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17, {}
FATAL: Error: 4 errors occured -- cannot continue.
C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin checker reported failure. / Error: Plugin checker reported failure.
    at C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
    at async ScheduleNode (C:\Users\Robert Holt\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Plugin checker reported failure.
[9.91 s] Shutting Down.
[9.91 s] Exiting.
```

**Comment by daviwil** [comment]
Spoke with @rjmholt over Teams and determined that adding `modelerfour.flatten-models` and `modelerfour.flatten-payloads` parameters resolved the issue.  There are known issues in the Blob service spec related to duplicated schema names inside of schemas that are meant to be flattened.
